### ISSUE TITLE
How to speed up dataloading for Meta-Dataset?

### ISSUE THREAD

**Issue by LiJunnan1992** [yinboc/few-shot-meta-baseline#27]
Hi, thanks for the amazing code!

I'm running the training script for meta-dataset, but found the GPU utilization rate to be very low. I'm not very familiar with tensorflow, could you help me point out how to speed up the dataloading? Thanks a lot!

**Comment by yinboc** [comment]
Thanks for your interest in our work!

I am also not quite familiar with tensorflow, thus I remember that I copied their original tensorflow code (in this [repo](https://github.com/google-research/meta-dataset)) for data loading. Did you try their original code and see the GPU utilization?

**Comment by LiJunnan1992** [comment]
Hi, it seems the speed bottleneck is because of the pytorch augmentations performed in the for loop. I have tried to use multi-processing but cannot get a speed-up due to communication overhead. Please let me know if you have any good solution, appreciate it!

**Comment by yinboc** [comment]
I see. I also did not find a good way for doing this more efficiently. Ideally, we may want to have these augmentations in the tensorflow code, but I am not very familar with tensorflow and just used the tensorflow loader as a black box.
