### ISSUE TITLE
inconsistency of augmentation between classifier-baseline and meta-baseline

### ISSUE THREAD

**Issue by Tsingularity** [yinboc/few-shot-meta-baseline#28]
Thanks for the great work!

For tiered imagenet, I am confused that why using "resize" augmentation during pre-training (classifier-baseline) but using default one (directly resize to final resolution 80?) during meta fine-tuning? Is there any specific reason behind this inconsistency?

Thanks!

**Comment by yinboc** [comment]
Thanks for your interest in our work!
This is because we empirically observe that it achieves a slightly better performance when not to have augmentation during the meta fine-tuning stage.

**Comment by Tsingularity** [comment]
cool, thanks for the update!
