### ISSUE TITLE
训练自己的数据集

### ISSUE THREAD

**Issue by yuandongbo123** [yinboc/few-shot-meta-baseline#36]
请问如何训练自己的数据集呢，在baseline_classfiy 里有需要加载序列化文件，是不是也需要将自己的文件存储成mini_imagnenet的序列化形式，再进行加载呢？

**Comment by yinboc** [comment]
你好，这个repo主要为了复现paper结果，使用自己的数据集需要仿照mini_imagenet的格式或者自己写pytorch的Dataset class.

**Comment by yuandongbo123** [comment]
谢谢，已经解决了。


| |
yuandongbo
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年10月6日 02:28，Yinbo ***@***.***> 写道：

Closed #36.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
